/* eslint-disable import/no-anonymous-default-export */

// Esse arquivo simula um bando de dados onde seria buscado as informações para a aplicação
export default [
    {"photo": "https://github.com/ricmaloy.png",              "name": "ricardo",     "email" : "ricardo@email.com",         "number":"(34) 99296-6193", "location" : "uberlândia - mg",        "status": "aberto"},
    {"photo": "https://github.com/ggardusi.png",              "name": "gustavo",     "email" : "gardusii@email.com",        "number":"(11) 98545-1213", "location" : "mariana - mg",           "status": "aberto"},
    {"photo": "https://github.com/felipebelisario.png",       "name": "felipe",      "email" : "felbelisario@ufu.br",       "number":"(34) 93218-9874", "location" : "divinópolis - mg",       "status": "aberto"},
    {"photo": "https://github.com/lorenaelias.png",           "name": "lorena elias","email" : "felbelisario@ufu.br",       "number":"(34) 93218-9874", "location" : "ouro preto - mg",        "status": "aberto"},
    {"photo": "https://github.com/augusto-moraes.png",        "name": "augusto",     "email" : "augusto@email.com",         "number":"(34) 99848-5489", "location" : "uberlândia - mg",        "status": "aberto"},
    {"photo": "https://github.com/jonasschmedtmann.png",      "name": "jonas",       "email" : "jjonas@email.com",          "number":"(11) 98696-1773", "location" : "mariana - mg",           "status": "aberto"},
    {"photo": "https://github.com/guilhermealvesc.png",       "name": "guilherme",   "email" : "guilhermebac@ufu.br",       "number":"(34) 93748-9874", "location" : "divinópolis - mg",       "status": "aberto"},
    {"photo": "https://github.com/pereiraadiel.png",          "name": "adiel",       "email" : "adiel.pereira@ufu.br",      "number":"(34) 99415-9874", "location" : "ouro preto - mg",        "status": "aberto"},
    {"photo": "https://github.com/adrielerodr.png",           "name": "ana luisa",   "email" : "analuizasilva@bol.com.br",  "number":"(34) 99852-6969", "location" : "são paulo - sp",         "status": "aberto"},
    {"photo": "https://github.com/marcosbarker.png",          "name": "davi luís",   "email" : "luisdavi@email.com.br",     "number":"(11) 99876-5432", "location" : "petrópolis - rj",        "status": "aberto"},
    {"photo": "https://github.com/pedro-rodrigues18.png",     "name": "filipe",      "email" : "felipe.augusto@usp.br",     "number":"(34) 99415-9874", "location" : "suzano - sp",            "status": "aberto"},
    {"photo": "https://github.com/rdelbem.png",               "name": "renato",      "email" : "renatofialho@hotmail.com",  "number":"(55) 92587-4774", "location" : "joinville - sc",         "status": "aberto"},
    {"photo": "https://github.com/mariarubinger.png",         "name": "isabela",     "email" : "isasilva@email.com.br",     "number":"(34) 92114-4369", "location" : "poço fundo - mg",        "status": "aberto"},
    {"photo": "https://github.com/Gabriel-f-r-bojikian.png",  "name": "leandro",     "email" : "leandrodev@email.com.br",   "number":"(11) 99852-7369", "location" : "são paulo - sp",         "status": "aberto"},
    {"photo": "https://github.com/taynaramos.png",            "name": "lívia",       "email" : "livia.martins@ufu.br",      "number":"(34) 99652-9574", "location" : "uberlândia - mg",        "status": "aberto"},
    {"photo": "https://github.com/Valmar31.png",              "name": "tiago",       "email" : "tiagooliveira@email.com.br","number":"(34) 98742-2525", "location" : "corumbá - ms",           "status": "aberto"},
    {"photo": "https://github.com/Minozzzi.png",              "name": "guilherme",   "email" : "guifernandes@email.com.br", "number":"(34) 95236-5725", "location" : "curitiba - pr",          "status": "aberto"},
    {"photo": "https://github.com/LucasCascao.png",           "name": "guilherme",   "email" : "guifernandes@email.com.br", "number":"(34) 99580-3584", "location" : "pato branco - pr",       "status": "aberto"},
    {"photo": "https://github.com/Fernanda-Kipper.png",       "name": "luana",       "email" : "luanasonza@gmail.com.br",   "number":"(11) 99952-3694", "location" : "pato branco - pr",       "status": "aberto"},
    
    
    {"photo": "https://github.com/tobiasMarion.png",          "name": "luciano",     "email" : "lucianorfe@hotmail.com.br", "number":"(34) 55442-5487", "location" : "belo horizonte - mg",    "status": "negado"},
    {"photo": "https://github.com/nycolle-fazolo.png",        "name": "letícia",     "email" : "letpereira@hotmail.com",    "number":"(55) 97998-7487", "location" : "uberlândia - mg",        "status": "negado"},
    {"photo": "https://github.com/NayanneBatista.png",        "name": "isadora",     "email" : "isadora.lemes@ufu.br",      "number":"(34) 99269-3325", "location" : "balneário camboriú - sc","status": "negado"},
    {"photo": "https://github.com/romsishiyama.png",          "name": "luciana",     "email" : "leciana@hotmail.com.br",    "number":"(34) 98524-6325", "location" : "belo horizonte - mg",    "status": "negado"},
    {"photo": "https://github.com/marciosamuel.png",          "name": "marcos paulo","email" : "marcospaulo@hotmail.com",   "number":"(11) 96358-8529", "location" : "uberlândia - mg",        "status": "negado"},
    {"photo": "https://github.com/rafaelfachinelli.png",      "name": "rafael",      "email" : "rafaellemestoia@ufu.br",    "number":"(34) 99269-3325", "location" : "balneário camboriú - sc","status": "negado"},
    {"photo": "https://github.com/felipebeskow.png",          "name": "diego",       "email" : "diegoss@email.com",         "number":"(11) 98696-1773", "location" : "mariana - mg",           "status": "negado"},
    {"photo": "https://github.com/viniciuscondev.png",        "name": "guilherme",   "email" : "guilhermeasd@ufu.br",       "number":"(34) 93748-9874", "location" : "divinópolis - mg",       "status": "negado"},
    {"photo": "https://github.com/rafaelalmagro.png",         "name": "ricardo",     "email" : "ricardo.pereira@ufu.br",    "number":"(34) 99415-9874", "location" : "ouro preto - mg",        "status": "negado"},
    {"photo": "https://github.com/garimasingh128.png",        "name": "ana luisa",   "email" : "analuizasilva@bol.com.br",  "number":"(34) 99852-6969", "location" : "são paulo - sp",         "status": "negado"},
    {"photo": "https://github.com/gabrielanori.png",          "name": "leticia",     "email" : "letpereira@email.com.br",   "number":"(11) 99876-5432", "location" : "petrópolis - rj",        "status": "negado"},
    {"photo": "https://github.com/raphaelcarneiro.png",       "name": "raphael",     "email" : "rapha.augusto@usp.br",      "number":"(34) 99415-9874", "location" : "suzano - sp",            "status": "negado"},
    {"photo": "https://github.com/juniormendes96.png",        "name": "rodrigo",     "email" : "rodrigofialho@hotmail.com", "number":"(55) 92587-4774", "location" : "joinville - sc",         "status": "negado"},
    {"photo": "https://github.com/cintyagg.png",              "name": "cecilia",     "email" : "cec.ilia@email.com.br",     "number":"(34) 92114-4369", "location" : "poço fundo - mg",        "status": "negado"},
    {"photo": "https://github.com/Markimg22.png",             "name": "leandro",     "email" : "leandrodev@email.com.br",   "number":"(11) 99852-7369", "location" : "são paulo - sp",         "status": "negado"},
    {"photo": "https://github.com/EmanuelcPereira.png",       "name": "andré",       "email" : "andre.martins@ufu.br",      "number":"(34) 99652-9574", "location" : "uberlândia - mg",        "status": "negado"},
    {"photo": "https://github.com/raulpy271.png",             "name": "santiago",    "email" : "santiagosouza@email.com.br","number":"(34) 98742-2525", "location" : "corumbá - ms",           "status": "negado"},
    {"photo": "https://github.com/laisbasso.png",             "name": "laisa",       "email" : "laisafernande@email.com.br","number":"(34) 95236-5725", "location" : "curitiba - pr",          "status": "negado"},
    {"photo": "https://github.com/teixeira83.png",            "name": "rafael",      "email" : "rafele@email.com.br",       "number":"(34) 99580-3584", "location" : "pato branco - pr",       "status": "negado"},
    {"photo": "https://github.com/ggsant.png",                "name": "beatriz",     "email" : "bibsaguiar@gmail.com.br",   "number":"(11) 99952-3694", "location" : "pato branco - pr",       "status": "negado"},


    {"photo": "https://github.com/otiagosoares.png",          "name": "douglas",     "email" : "douglascsv@gmail.com",      "number":"(55) 99159-1143", "location" : "uberada - mg",           "status": "atendido"},
    {"photo": "https://github.com/ronistone.png",             "name": "ronistone",   "email" : "ronipedra@gmail.com.br",    "number":"(34) 97536-1243", "location" : "uberlândia - mg",        "status": "atendido"},
    {"photo": "https://github.com/pedrodiogo219.png",         "name": "pedro diogo", "email" : "pediogo@email.com",         "number":"(34) 97226-4843", "location" : "uberlândia - mg",        "status": "atendido"},
    {"photo": "https://github.com/nunesg.png",                "name": "gustavo",     "email" : "nunneraff@email.com",       "number":"(11) 99254-7413", "location" : "pelotas - rs",           "status": "atendido"},
    {"photo": "https://github.com/yagovfcastro.png",          "name": "iago",        "email" : "iagocastro@gmail.com",      "number":"(11) 97459-8843", "location" : "uberada - mg",           "status": "atendido"},
    {"photo": "https://github.com/vhmarra.png",               "name": "victor hugo", "email" : "vitinmarre@gmail.com.br",   "number":"(34) 91254-1548", "location" : "uberlândia - mg",        "status": "atendido"},
    {"photo": "https://github.com/rabispedro.png",            "name": "pedro paulo", "email" : "ppaulo@email.com",          "number":"(34) 99874-6521", "location" : "uberlândia - mg",        "status": "atendido"},
    {"photo": "https://github.com/washingtonsoares.png",      "name": "washington",  "email" : "washington@email.com",      "number":"(11) 99254-1427", "location" : "pelotas - rs",           "status": "atendido"},
    {"photo": "https://github.com/MateusCohuzer.png",         "name": "guilherme",   "email" : "guilhermeasd@ufu.br",       "number":"(34) 93748-9874", "location" : "divinópolis - mg",       "status": "atendido"},
    {"photo": "https://github.com/TrindadeThiago.png",        "name": "ricardo",     "email" : "ricardo.pereira@ufu.br",    "number":"(34) 99415-9874", "location" : "ouro preto - mg",        "status": "atendido"},
    {"photo": "https://github.com/vanessafsoares.png",        "name": "ana luisa",   "email" : "analuizasilva@bol.com.br",  "number":"(34) 99852-6969", "location" : "são paulo - sp",         "status": "atendido"},
    {"photo": "https://github.com/natcecilio.png",            "name": "leticia",     "email" : "letpereira@email.com.br",   "number":"(11) 99876-5432", "location" : "petrópolis - rj",        "status": "atendido"},
    {"photo": "https://github.com/RodolfoSarkisRocha.png",    "name": "raphael",     "email" : "rapha.augusto@usp.br",      "number":"(34) 99415-9874", "location" : "suzano - sp",            "status": "atendido"},
    {"photo": "https://github.com/capelaum.png",              "name": "rodrigo",     "email" : "rodrigofialho@hotmail.com", "number":"(55) 92587-4774", "location" : "joinville - sc",         "status": "atendido"},
    {"photo": "https://github.com/PamelaFeijo.png",           "name": "cecilia",     "email" : "cec.ilia@email.com.br",     "number":"(34) 92114-4369", "location" : "poço fundo - mg",        "status": "atendido"},
    {"photo": "https://github.com/FZamberlam.png",            "name": "leandro",     "email" : "leandrodev@email.com.br",   "number":"(11) 99852-7369", "location" : "são paulo - sp",         "status": "atendido"},
    {"photo": "https://github.com/robertosousa1.png",         "name": "andré",       "email" : "andre.martins@ufu.br",      "number":"(34) 99652-9574", "location" : "uberlândia - mg",        "status": "atendido"},
    {"photo": "https://github.com/arthurvdiniz.png",          "name": "santiago",    "email" : "santiagosouza@email.com.br","number":"(34) 98742-2525", "location" : "corumbá - ms",           "status": "atendido"},
    {"photo": "https://github.com/biancaespindola.png",       "name": "laisa",       "email" : "laisafernande@email.com.br","number":"(34) 95236-5725", "location" : "curitiba - pr",          "status": "atendido"},
    {"photo": "https://github.com/squillace91.png",           "name": "rafael",      "email" : "rafele@email.com.br",       "number":"(34) 99580-3584", "location" : "pato branco - pr",       "status": "atendido"},
    {"photo": "https://github.com/psousaraquels.png",         "name": "beatriz",     "email" : "bibsaguiar@gmail.com.br",   "number":"(11) 99952-3694", "location" : "pato branco - pr",       "status": "atendido"},
]